apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-bbx5
  namespace: aronaldson-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:1046842a31d7a24e171375eb6e7c1a477213a655f0b892b80e35cb8a8eb3bfee
        name: my-go
        resources: {}
status: {}
